### ISSUE TITLE
Service events not streaming via events API.

### ISSUE THREAD

**Issue by nohaapav** [docker/for-azure#45] opened 2017-11-21 21:47 UTC
### Expected behavior

Service events should be streamed via events API since version 1.30.

### Actual behavior

Service events not streaming.

### Information

Service events stream should be supported since 1.30 [API](https://docs.docker.com/engine/api/version-history/#v130-api-changes) 

Docker version:

Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: false

### Steps to reproduce the behavior

  1. Create or update service in cluster while streaming from events API
  2. There are no messages regarding create/update/remove, just container events

**Comment by FrenchBen** [comment] 2017-11-21 23:42
Tried it with CE Edge:
```
~ $ docker service create --name nginx nginx
ijc0qbohyr5o6lbrftmx0a0yq
overall progress: 1 out of 1 tasks
1/1: running   [==================================================>]
verify: Service converged
~ $ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 00:21:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 00:26:36 2017
 OS/Arch:      linux/amd64
 Experimental: true
~ $
```
```
Welcome to Docker!
~ $ docker events
2017-11-21T22:39:14.006855446Z service create ijc0qbohyr5o6lbrftmx0a0yq (name=nginx)
```

Tried it with the latest Docker CE Stable
```
Welcome to Docker!
~ $ docker service create --name nginx nginx
qlo4e9hgrpws7mmfq52vjlcjw
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.
~ $ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
```
Welcome to Docker!
~ $ docker events
2017-11-21T23:41:41.544376334Z service create qlo4e9hgrpws7mmfq52vjlcjw (name=nginx)
```

Since both Edge and Stable are offering the functionality, I would recommend you upgrade to the latest stable.

**Comment by nohaapav** [comment] 2017-11-22 09:27
@FrenchBen Well the strange fact is that it works well with 17.06.2-ce installed locally on my machine. Wondering why its not working on same version of docker in azure ..

**Comment by FrenchBen** [comment] 2017-11-23 01:26
@nohaapav what's the git commit associated with the 17.06.2-ce on your machine? Perhaps there's a slight patch added?
With this working in our current Stable and Edge release, and this not being Docker EE, I can only recommend to upgrade in order to see the functionality, or go through the debugging steps yourself.

Closing the issue, but feel free to add comments to it here, especially if you get to the root cause.

**Closed as completed by FrenchBen** 2017-11-23 01:26 UTC

**Comment by nohaapav** [comment] 2017-11-24 11:34
@FrenchBen git commit is completely the same within both engines (azure / local) .. Let's upgrade the engine then.
