### ISSUE TITLE
Volumes with `cloudstor:azure` driver prevent set timeStamp

### ISSUE THREAD

**Issue by raphaelquati** [docker/for-azure#17] opened 2017-05-20 04:43 UTC
I've created a jenkins service:

```
  docker service create --name jenkins \
       --mount type=volume,volume-driver=cloudstor:azure,source={{.Service.Name}}-{{.Task.Slot}}-
   vol,destination=/var/jenkins_home  \
        -p 8080:8080 -p 4040:4040 jenkinsci/jenkins

```
But Jenkins stops with exception:

SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: java.lang.RuntimeException: java.io.IOException: Failed to set the timestamp of /var/jenkins_home/secrets/initialAdminPassword to 1495234797271
at hudson.WebAppMain$3.run(WebAppMain.java:252)
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to set the timestamp of /var/jenkins_home/secrets/initialAdminPassword to 1495234797271
at jenkins.install.InstallState$3.initializeState(InstallState.java:107)
at jenkins.model.Jenkins.setInstallState(Jenkins.java:1060)
at jenkins.install.InstallUtil.proceedToNextStateFrom(InstallUtil.java:96)
at jenkins.model.Jenkins.<init>(Jenkins.java:950)
at hudson.model.Hudson.<init>(Hudson.java:86)
at hudson.model.Hudson.<init>(Hudson.java:82)
at hudson.WebAppMain$3.run(WebAppMain.java:235)
Caused by: java.io.IOException: Failed to set the timestamp of /var/jenkins_home/secrets/initialAdminPassword to 1495234797271
at hudson.FilePath$22.invoke(FilePath.java:1481)
at hudson.FilePath$22.invoke(FilePath.java:1470)
at hudson.FilePath.act(FilePath.java:997)
at hudson.FilePath.act(FilePath.java:975)
at hudson.FilePath.touch(FilePath.java:1470)
at jenkins.install.SetupWizard.init(SetupWizard.java:114)
at jenkins.install.InstallState$3.initializeState(InstallState.java:105)
... 6 more

swarm-manager000000:~$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by ddebroy** [comment] 2017-05-30 16:56
@raphaelquati We have a workaround for this issue that we will release shortly as part of 17.06 release. Basically CIFS is used internally for the storage by cloudstor and CIFS creates all files with the UID/GID specified during the volume mount. We always defaulted to root UID for CIFS in cloudstor causing the above issue since Jenkins installation always uses a Jenkins user with UID 1000. We will make the UID/GID configurable for cloudstor in Azure so that when installing Jenkins (or something with similar UID restrictions), you can specify the UID of the corresponding user for the storage as well.

**Comment by ddebroy** [comment] 2017-05-30 17:01
@raphaelquati also checkout https://github.com/docker/for-azure/issues/15#issuecomment-302261200 for a more immediate workaround before the above becomes available.

**Comment by ddebroy** [comment] 2017-05-30 18:20
Duplicate of https://github.com/docker/for-azure/issues/15

**Closed by ddebroy** 2017-05-30 18:20 UTC
