### ISSUE TITLE
Unable to connect to Manager and Worker VMSS's after shutting down or restarting

### ISSUE THREAD

**Issue by RothAndrew** [docker/for-azure#48] opened 2018-01-15 20:54 UTC
### Expected behavior
1. Restart or Deallocate > Start the Manager and Worker VMSS's
2. Start both VMSS's
3. Able to SSH into manager. Swarm is running as before restart.

### Actual behavior
1. SSH using PuTTY returns "Network error: Connection refused"
2. The website that was running returns INET_E_RESOURCE_NOT_FOUND
3. Curl returns `curl : Unable to connect to the remote server`

### Steps to reproduce the behavior
1. Spin up a Docker for Azure swarm using the [template](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fdownload.docker.com%2Fazure%2Fstable%2FDocker.tmpl)
2. Wait for everything to get provisioned, test by deploying a simple stack, etc
3. Worker VMSS > Deallocate, wait till that completes
4. Manager VMSS > Deallocate, wait till completion
5. Manager VMSS > Start, wait till completion
6. Worker VMSS > Start, wait till completion

**Comment by jemnem** [comment] 2018-01-17 02:40
yep, I found the same issue the other day

**Comment by JamesCarscadden** [comment] 2018-01-19 15:37
I have had this issue for a while as well, it would appear nobody ever restarts their cluster. I would like to be able to shut my dev cluster down every evening in order to save costs. It looks like the "agent" container (which actually hosts ssh on the cluster) doesn't come back up after a restart.

**Comment by JamesCarscadden** [comment] 2018-01-19 15:39
I should also note that I've tried updating the RestartPolicy on the "Agent" container to "Always" -- this doesn't appear to help. There may be other problems preventing that container from coming up after a restart

**Comment by RothAndrew** [comment] 2018-01-19 15:48
One thing I noticed is that if I horizontally scale to 0 instances rather
than deprovisioning I am able to SSH back in once I have reverse that
process. The problem then is that the manager that I've SSHed in to is no
longer a part of the swarm.

**Comment by eyz** [comment] 2018-01-25 15:28
I suggested that a next step could likely be to gain console access to the VM(s) and check via `netstat -lnp` if SSH is in fact listening, and which interface it's bound to. It sounds like it's not bound to the expected interface, or firewalled off for some reason. I found an article on Azure console usage @ http://www.garethjones294.com/console-access-to-azure-virtual-machines/

**Comment by adijes** [comment] 2018-02-13 20:24
Is this issue fixed? Any workarounds? I'm having the exact same issue. After deallocating - the docker swarm is not reachable at all using SSH. What should I do?
As I see it, I cannot use this as production environment.

**Comment by RothAndrew** [comment] 2018-02-13 20:46
After learning more about how cluster orchestration works it seems like
it's not really meant to be able to survive a complete shutdown of the
cluster. I've seen the phrase "maintain quorum" thrown around a lot. Seems
like in a production environment if you're running at least 5 nodes you can
maintain Quorum even if several of your nodes die.

**Comment by adijes** [comment] 2018-02-13 20:49
@RothAndrew this is not correct, if you create a swarm with 5 nodes, and the scale set shuts down for some reason, this is not recoverable. No connection at all. You are locked out from the docker swarm forever.

**Comment by FrenchBen** [comment] 2018-02-14 19:30
@adijes IMHO, `I cannot use this as production environment` and the word `deallocating` do not belong in the same sentence. If you can deallocate something, then it's not a production environment. 
If this is a real issue for your setup, feel free to upgrade to our paid support plan. ;)

I believe that this issue is linked to the container flags not being observed in the latest release of LinuxKit. We're still investigating this issue in order to determine the source. 
Looking at the boot logs from all instances, they appear to come up properly and have docker running as expected. 
The issue is the agent/ssh container isn't started back up once the instance is up. 

You can start a new instance by scaling the cluster up, but since we're unable to get a token from the leader to join the swarm, the node will not be added to the swarm.

**Comment by punitganshani** [comment] 2018-02-21 07:08
This is really required for Development Environment. Any guideline/fix?

**Comment by FrenchBen** [comment] 2018-02-27 02:44
@punitganshani Were you able to reproduce this in the latest Edge release?

**Comment by JamesCarscadden** [comment] 2018-02-27 16:52
I tried this again today with the latest edge template. Still have the same problem.
It would seem based on the boot logs, that it's trying to start the agent container, but the logs end before I can see what actually happens.

`.... regular system boot stuff
.... docker loading layers

Loaded image: docker4x/agent-azure:18.01.0-ce-azure1
 [ ok ]
 * Pulling Windows Azure Linux Agent container
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 * Pulling Windows Azure Linux Agent container
 * Running Windows Azure Linux Agent container
sshkey
<skey>
passwd: password for docker changed by root
 * /home/docker/.ssh: creating directory`

the logs end at that point.

**Comment by FrenchBen** [comment] 2018-02-27 18:21
@JamesCarscadden it doesn't seem isolated to azure/agent only stuff. I'm able to replicate this now 💯 with Docker for Mac.

**Comment by ghost** [comment] 2018-03-03 13:02
I’m having the same issue. For Dev/Test we really need to be able to deallocate.

**Comment by ghost** [comment] 2018-03-12 12:44
I was able to 'fix' this by deploying my swarm via docker cloud swarm beta using the latest edge release. Ssh is available after restart, though sometime it will say connection refused a few times, but it does eventually come back.

**Comment by FrenchBen** [comment] 2018-03-14 18:29
@devkws this should be fixed on the latest Edge+Stable.

**Closed as completed by FrenchBen** 2018-03-14 18:29 UTC

**Comment by vesylapp** [comment] 2018-04-26 23:17
@FrenchBen This doesn't seem to be fixed in 18.03.0-ce.

After restarting one of my managers, I can no longer SSH into it.  The `agent` container is not running inside it.  The restart policy specified in the image is `unless-stopped`.

And, I tried to run it manually using portainer, but the container can't find SSH keys and so it fails.

**Comment by th3000** [comment] 2018-11-06 09:57
Why was this issue closed even it isn't solved?

**Comment by christianacca** [comment] 2019-03-07 08:05
I hit this issue as well after deallocating a freshly minted swarm cluster created using this docker for azure ARM template.

This issue should at least be documented over here: https://docs.docker.com/docker-for-azure/

Ideally, with a big warning not to deallocate the manager scale set, with steps to how to recover if this ever happens.

Thanks
Christian

**Comment by klchung** [comment] 2019-05-22 05:35
All,
Encountered the same issue with the latest CE version - has anyone found a solution or workaround on how to reconnect to the swarm manager after a restart of the VMSS?  Please advise and thanks in advance.
